/**
 * Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef __GST_DSRETAILYTICS_H__
#define __GST_DSRETAILYTICS_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

/* Open CV headers */
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"

#include <cuda.h>
#include <cuda_runtime.h>
#include "nvbufsurface.h"
#include "nvbufsurftransform.h"
#include "gst-nvquery.h"
#include "gstnvdsmeta.h"
#include "dsretailytics_lib/dsretailytics_lib.h"
#include "nvtx3/nvToolsExt.h"

#include <condition_variable>
#include <mutex>
#include <thread>

/* Package and library details required for plugin_init */
#define PACKAGE "dsretailytics"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION "IRL NCAI plugin for generating analytics for retail application with DeepStream on DGPU/Jetson"
#define BINARY_PACKAGE "NVIDIA DeepStream retail analytics generation plugin"
#define URL "http://ncai.nust.edu.pk/"


G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDsRetailytics GstDsRetailytics;
typedef struct _GstDsAppAnalytics GstDsAppAnalytics;
typedef struct _GstDsRetailyticsClass GstDsRetailyticsClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DSRETAILYTICS (gst_dsretailytics_get_type())
#define GST_DSRETAILYTICS(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_DSRETAILYTICS,GstDsRetailytics))
#define GST_DSRETAILYTICS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_DSRETAILYTICS,GstDsRetailyticsClass))
#define GST_DSRETAILYTICS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DSRETAILYTICS, GstDsRetailyticsClass))
#define GST_IS_DSRETAILYTICS(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_DSRETAILYTICS))
#define GST_IS_DSRETAILYTICS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_DSRETAILYTICS))
#define GST_DSRETAILYTICS_CAST(obj)  ((GstDsRetailytics *)(obj))

/** Maximum batch size to be supported by dsretailytics. */
#define MAX_CLASS_IDS_PER_ANALYTICS G_MAXINT

struct _GstDsAppAnalytics
{
  // Boolean indicating if to generate this analytics or not
  gboolean enable;

  // Class ids to this analytics operation on
  gint class_ids[MAX_CLASS_IDS_PER_ANALYTICS];

  // Number of class ids attached to this analytics object
  gint num_classes;
};

struct _GstDsRetailytics
{
  GstBaseTransform base_trans;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;

  // Context of the custom algorithm library
  DsRetailyticsCtx *dsretailyticslib_ctx;

  // Boolean indicating if to generate real-world coordinates for objects
  GstDsAppAnalytics world_coords_analytics;
};

/** Boiler plate stuff */
struct _GstDsRetailyticsClass
{
  GstBaseTransformClass parent_class;
};

GType gst_dsretailytics_get_type (void);

G_END_DECLS
#endif /* __GST_DSRETAILYTICS_H__ */
